use_frameworks!

platform :ios, '10.0'

target 'GemvarySmartHomeSDK_Example' do
  pod 'GemvarySmartHomeSDK', :path => '../'

  target 'GemvarySmartHomeSDK_Tests' do
    inherit! :search_paths

    
  end
end
